# Generated by Django 3.0.14 on 2022-02-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dept',
            name='id',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
