# Generated by Django 3.0.14 on 2022-02-17 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0003_auto_20220217_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='USN',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, primary_key='True', serialize=False),
            preserve_default=False,
        ),
    ]
