# Generated by Django 3.0.14 on 2022-02-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0004_auto_20220217_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='USN',
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
