# Generated by Django 3.0.14 on 2022-02-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0005_auto_20220217_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='USN',
            field=models.CharField(default=1, max_length=100, primary_key='True', serialize=False),
            preserve_default=False,
        ),
    ]
